use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '9.3'

target 'Wendy-iOS_Example' do
  pod 'Wendy', :path => '../'
  pod 'SnapKit', '~> 4.0.0'

  target 'Wendy-iOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
