use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '10.0'

target 'Wendy_Example' do
  pod 'Wendy', :path => '../'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'

  target 'Wendy_Tests' do
    inherit! :search_paths
  end
end
