use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '10.0'

def commonDependencies
  pod 'Wendy', :path => '../'
  pod 'SnapKit', '~> 5.0.1'  
end 

def testingDependencies
  pod 'SwiftLint'  
  pod 'SwiftFormat/CLI'
end

target 'Wendy_Example' do
  commonDependencies()  
end

target 'Wendy_Tests' do
  commonDependencies()
  testingDependencies()
end