name: Setup semantic-release 
description: Install all of the tools that the server needs to run semantic-release

runs:
  using: "composite"
  steps:
  # semantic-release requires newer versions of node then what is bundled in github action runner. 
  - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
    with:
      node-version: 'lts/*'

  # Using conventional v7 to fix bug https://github.com/semantic-release/release-notes-generator/issues/633
  - name: Install semantic-release plugins that we need for deployment of this project 
    run: >
      npm install       
      conventional-changelog-conventionalcommits
      @semantic-release/github 
      @semantic-release/git 
      semantic-release-recovery@beta
      semantic-release-cocoapods 
      semantic-release-precheck
    shell: bash
