name: Setup semantic-release 
description: Install all of the tools that the server needs to run semantic-release

runs:
  using: "composite"
  steps:
  # semantic-release requires newer versions of node then what is bundled in github action runner. 
  - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
    with:
      node-version: 'lts/*'

  - name: Install semantic-release plugins that we need for deployment of this project 
    run: >
      npm install 
      conventional-changelog-conventionalcommits 
      @semantic-release/github 
      @semantic-release/git 
      semantic-release-recovery@beta
      semantic-release-cocoapods 
      semantic-release-precheck
    shell: bash