# To run, you must install: https://taskfile.dev/installation/

version: '3'

tasks:
  clean:
    cmds:
      - rm -rf Wendy.xcresult
      - rm -rf .build

  build:
    cmds:
      - task: clean 
      - pod lib lint --allow-warnings
      - xcrun xcodebuild -skipMacroValidation -skipPackagePluginValidation build -scheme Wendy -destination generic/platform=ios | xcbeautify

  # to create command, get fastlane scan to run all tests, then you can copy the command it creates and run it directly. This is a small speed improvement. 
  test:
    cmds:
      - task: clean
      - xcodebuild -scheme Wendy -destination 'platform=iOS Simulator,name=iPhone 15' -derivedDataPath .build/derivedData -enableCodeCoverage YES build-for-testing | xcbeautify
      - xcodebuild -scheme Wendy -destination 'platform=iOS Simulator,name=iPhone 15' -derivedDataPath .build/derivedData -enableCodeCoverage YES test-without-building | xcbeautify
  
  # Resourced used to create this command:
  # https://github.com/michaelhenry/swifty-code-coverage/
  coverage:
    preconditions:
      - test -d .build/
    cmds:
      - xcrun llvm-cov export "$(find .build -name WendyTests.xctest | tail -n1)/WendyTests" -instr-profile=$(find .build -name *.profdata | tail -n1) -ignore-filename-regex=Tests/* -format=lcov > .build/lcov.info
      - xcrun llvm-cov report "$(find .build -name WendyTests.xctest | tail -n1)/WendyTests" -instr-profile=$(find .build -name *.profdata | tail -n1) -ignore-filename-regex=Tests/* -use-color
  
