name: App
options:
  bundleIdPrefix: earth.levi.wendy
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: Source
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGNING_ALLOWED: NO