# To run, you must install: https://taskfile.dev/installation/

version: '3'

tasks:
  xcodegen_clean:
    internal: true 
    cmds:
      - rm -rf *.xcodeproj
      - rm -rf *.xcworkspace  

  generate_xcode_project:
    internal: true # meant to be called by one of the child tasks 
    cmds:
      - task: xcodegen_clean
      - ../../.nest/bin/xcodegen generate --spec {{.XCODE_GEN_SPEC_FILENAME}}        

  generate_xcode_project_spm:
    cmds:
      - task: generate_xcode_project
        vars:
          XCODE_GEN_SPEC_FILENAME: project-spm.yml
  
  build: 
    internal: true # meant to be called by one of the child tasks
    cmds:
      - task: generate_xcode_project_spm
      - set -o pipefail && xcrun xcodebuild clean build -scheme App -destination 'generic/platform=iOS Simulator' | xcbeautify

  build_spm: # meant to be called in a subdirectory in app/ such as app/ios/
    cmds: 
      - task: build
