# To run, you must install: https://taskfile.dev/installation/

version: '3'

tasks:
  xcodegen_clean:
    internal: true 
    cmds:
      - rm -rf *.xcodeproj
      - rm -rf *.xcworkspace  

  generate_xcode_project:
    internal: true # meant to be called by one of the child tasks 
    cmds:
      - task: xcodegen_clean
      - mint run --mintfile ../../Mintfile xcodegen generate --spec {{.XCODE_GEN_SPEC_FILENAME}}        

  generate_xcode_project_spm:
    cmds:
      - task: generate_xcode_project
        vars:
          XCODE_GEN_SPEC_FILENAME: project-spm.yml
  
  generate_xcode_project_cocoapods:
    cmds:
      - task: generate_xcode_project
        vars:
          XCODE_GEN_SPEC_FILENAME: project.yml
      - pod install

  build: 
    internal: true # meant to be called by one of the child tasks
    cmds: 
      - set -o pipefail && xcrun xcodebuild clean build {{.XCODEBUILD_ARGS}} -scheme App | xcbeautify

  build_spm: # meant to be called in a subdirectory in app/ such as app/ios/
    cmds: 
      - task: generate_xcode_project_spm
      - task: build

  build_cocoapods: # meant to be called in a subdirectory in app/ such as app/ios/
    cmds: 
      - task: generate_xcode_project_cocoapods
      - task: build
        vars:
          XCODEBUILD_ARGS: -workspace App.xcworkspace