name: Setup iOS
description: Setup CI with iOS development tools to compile and test iOS source code. 

inputs:
  repo-token:
    description: 'GITHUB_TOKEN' 

runs:
  using: "composite"
  steps:
  - name: Install development tool, Taskfile
    uses: arduino/setup-task@v2
    with:
      version: 3.x
      repo-token: ${{ inputs.repo-token }}

  - name: Install package manager tool, Nest
    run: curl -s https://raw.githubusercontent.com/mtj0928/nest/main/Scripts/install.sh | bash
    shell: bash
  
  - name: Install development tools with Nest
    run: task install_dev_tools
    shell: bash

  - name: Generate code to allow project to compile 
    run: task codegen 
    shell: bash