name: Setup iOS
description: Setup CI with iOS development tools to compile and test iOS source code. 

inputs:
  repo-token:
    description: 'GITHUB_TOKEN' 

runs:
  using: "composite"
  steps:
  - name: Install XCode 
    uses: maxim-lobanov/setup-xcode@v1
    with:
      xcode-version: "15"

  - name: Install development tool, Taskfile
    uses: arduino/setup-task@v2
    with:
      version: 3.x
      repo-token: ${{ inputs.repo-token }}

  - name: Install package manager, Mint
    uses: irgaly/setup-mint@v1

  - name: Generate code to allow project to compile 
    run: task codegen 
    shell: bash