name: Setup iOS
description: Setup CI with iOS development tools to compile and test iOS source code. 

inputs:
  repo-token:
    description: 'GITHUB_TOKEN' 

runs:
  using: "composite"
  steps:
  - name: Install XCode 
    uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1
    with:
      # Installs latest version of Xcode *installed in the github runner image*. 
      # Therefore, because the version of macos is fixed in workflow files, it's OK to use "latest" here. 
      xcode-version: "latest" 

  - name: Install development tool, Taskfile
    uses: arduino/setup-task@v2
    with:
      version: 3.x
      repo-token: ${{ inputs.repo-token }}

  - name: Install package manager, Mint
    uses: irgaly/setup-mint@2c1bb00ba290382666a79b4ece08381641aebeeb # v1

  - name: Generate code to allow project to compile 
    run: task codegen 
    shell: bash