
on:
  workflow_dispatch: # this workflow gets manually executed when commits merged into main 
  
jobs:
  deploy:
    runs-on: macos-latest
    permissions:
      contents: write # to make a git tag       
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup-ios
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-semantic-release      
      - uses: cycjimmy/semantic-release-action@v4
        with:
          branch: latest # have this match what this workflow triggers on
          semantic_version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

