on: [pull_request]

jobs:
  assert-formatted:
    name: Assert that code has been linted and formatted before merging
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ./.github/actions/setup-ios
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run swiftformat. Fail if any errors. 
        run: task format && git diff --exit-code
      - name: Run swiftlint. Fail if any errors. 
        run: task lint
