on: 
  pull_request:
  push:
    branches: [main]

concurrency: # cancel previous workflow run if one exists. 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task build

  run-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task test
    - run: task coverage
  
  compile-app:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Compile iOS app using SPM
      working-directory: app/ios
      run: task app:build_spm

      
