on: 
  pull_request:
  push:
    branches: [main]

concurrency: # cancel previous workflow run if one exists. 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task build

  run-tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task test
    - run: task coverage
    - name: Upload coverage for analysis 
      uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2
      with: 
        file: .build/lcov.info
      env:
        # try and speedup the action by homebrew not having to do more then it needs when installing the coveralls tool 
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
  
  compile-apps:
    runs-on: macos-14    
    strategy:
      fail-fast: false # if one build fails, dont stop trying to finish the other. 
      matrix:
        os: ["ios"]
        package-manager: ["cocoapods", "spm"]
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Compile ${{ matrix.os }} app, using package manager ${{ matrix.package-manager }}
      working-directory: app/${{ matrix.os }}
      run: task app:build_${{ matrix.package-manager }}

      