on: 
  pull_request:
  push:
    branches: [main]

concurrency: # cancel previous workflow run if one exists. 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task build

  run-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task test
    - run: task coverage
    - name: Upload coverage for analysis 
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
      with: 
        file: .build/lcov.info
      env:
        # try and speedup the action by homebrew not having to do more then it needs when installing the coveralls tool 
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
  
  compile-app:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Compile iOS app using SPM
      working-directory: app/ios
      run: task app:build_spm

      
