on: 
  pull_request:
  push:
    branches: [main]

concurrency: # cancel previous workflow run if one exists. 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task build

  run-tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-ios
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: task test
    - run: task coverage
    - name: Upload coverage for analysis 
      uses: coverallsapp/github-action@v2
      with: 
        file: .build/lcov.info
      env:
        # try and speedup the action by homebrew not having to do more then it needs when installing the coveralls tool 
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true